# compiled output
/dist
/node_modules

# Logs
logs
*.log
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# OS
.DS_Store

# Tests
/coverage
/.nyc_output

# IDEs and editors
/.idea
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace

# IDE - VSCode
.vscode

# GitHub
.git
.gitignore

# Docker
Dockerfile.dev
Dockerfile.prod
Dockerfile.prod.dockerignore
env-dev/*.yaml
env-prod

# Miscellaneous
*.md