version: '3.8'
services:
  pilliz-backend-prod:
    image: ghcr.io/pillizpro/pilliz-backend/prod:latest
    ports:
      - '8080:3000'
    env_file:
      - ./.env.prod
    depends_on:
      - pilliz-db-prod
    tty: true

  pilliz-db-prod:
    image: postgres
    container_name: env-prod_pilliz-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env.prod
      - ./.env.prod.internal
    volumes:
      - pilliz-db-prod-data:/var/lib/postgresql/data
volumes:
  pilliz-db-prod-data:
    name: pilliz-db-prod-data
