version: '3.8'
services:
  pilliz-backend-dev:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      target: dev
    image: pilliz-backend-dev
    container_name: env-dev_pilliz-backend-dev
    ports:
      - '8080:3000'
    volumes:
      - ../src:/app/src
      - ../test:/app/test
    depends_on:
      - pilliz-db-dev
    tty: true

  pilliz-backend-test:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      target: test
    image: pilliz-backend-test
    container_name: env-dev_pilliz-backend-test
    depends_on:
      - pilliz-db-dev
    tty: true

  pilliz-db-dev:
    image: postgres
    container_name: env-dev_pilliz-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env.dev
    volumes:
      - pilliz-db-dev-data:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    container_name: env-dev_dbadmin
    restart: always
    ports:
      - '8081:80'
    env_file:
      - ./.dbadmin.cred
    volumes:
      - dbadmin-data:/var/lib/pgadmin
volumes:
  pilliz-db-dev-data:
    name: pilliz-db-dev-data
  dbadmin-data:
    name: dbadmin-data
