version: '3.8'
services:
  pilliz-backend-staging-dev:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      target: staging
    image: pilliz-backend-staging-dev
    container_name: env-staging_pilliz-backend-staging-dev
    ports:
      - '8082:3000'
    volumes:
      - ../src:/app/src
    tty: true
