name: Build and Push Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      with_deploy:
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: metadata
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ inputs.environment }}
      #     tags: |
      #       type=ref,event=branch
      #       type=sha,format=long,prefix={{branch}}-
      #       type=raw,value=latest

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: "Dockerfile.prod"
      #     target: ${{ inputs.environment }}
      #     push: true
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
      - name: github ref
        run: echo ${{ github.ref }}

      - name: github ref name
        run: echo ${{ github.ref_name }}

      - name: github event
        run: echo ${{ github.event }}