name: Build and Push Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Build
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ inputs.environment }}
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix={{branch}}-
            type=raw,value=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "Dockerfile.prod"
          target: ${{ inputs.environment }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  deploy-env-on-server:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build-and-push-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Environment Stack on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.SSH_SCRIPT_TO_EXECUTE }}
