name: CI Linter

on:
  push:
    branches-ignore:
      - staging
      - prod
      - dependabot-updates
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.18.0', '18.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm latest version
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint files
        run: pnpm lint

      - if: matrix.node-version == '18.x'
        name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[+] Lint files'
          branch: GHA-lint-files
          title: '[+] Lint files'
          body: |
            Lint files via GitHub Actions
            - Auto-generated by this action [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            cicd_action
            auto_merge

      - if: ${{ steps.cpr.outputs.pull-request-number }}
        name: Merge Pull Request Created in Previous Step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pull Request ${{ steps.cpr.outputs.pull-request-number }} ${{ steps.cpr.outputs.pull-request-operation }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --body "[+] Lint files" --delete-branch
