name: Deploy Staging

on:
  workflow_run:
    workflows:
      - "CodeQL"
    types:
      - "completed"
    branches:
      - "staging"

permissions:
  contents: read
  packages: write

jobs:
  deploy_staging:
    uses: PillizPro/Pilliz-BackEnd/.github/workflows/build-and-push.yml@staging
    secrets: inherit
    with:
      environment: staging