name: Deploy Prod

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  packages: write

jobs:
  deploy-prod:
    uses: PillizPro/Pilliz-BackEnd/.github/workflows/build-and-push.yml@main
    secrets: inherit
    with:
      environment: prod
