name: Deploy Staging

on:
  workflow_run:
    workflows:
      - "CodeQL"
    types:
      - "completed"
    branches:
      - "NL-docker-image-staging"
      # - "staging"

permissions:
  contents: read
  packages: write

jobs:
  deploy_staging:
    uses: PillizPro/Pilliz-BackEnd/.github/workflows/build-and-push.yml@NL-docker-image-staging
    secrets: inherit
    with:
      environment: staging
  test:
    runs-on: ubuntu-latest
    steps:
      - name: github ref
        run: echo ${{ github.ref }}

      - name: github ref name
        run: echo ${{ github.ref_name }}
