name: Deploy Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  packages: write

jobs:
  deploy-staging:
    uses: PillizPro/Pilliz-BackEnd/.github/workflows/build-and-push.yml@main
    secrets: inherit
    with:
      environment: staging
