name: Update dependabot-updates branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request-dependabot-updates-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file for Pull Request
        run: "sed -i '$d' .github/workflows/pr-dependabot-updates-branch.txt && echo \"#\"Last update at: $(date +%D) $(date +%T) >> .github/workflows/pr-dependabot-updates-branch.txt"

      - name: Create Pull Request
        id: cpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[+] Update dependabot-updates branch to latest version'
          branch: GHA-update-dependabote-updates-branch
          delete-branch: true
          base: dependabot-updates
          title: '[+] Update dependabot-updates branch to latest version'
          body: |
            Update dependabot-updates branch via GitHub Actions
            - Auto-generated by this action [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            cicd_action
            update_branch
