name: Update dependabot-updates branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request-dependabot-updates-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B dependabot-updates -H ${{ github.ref_name }} --title '[+] Update dependabot-updates branch to latest version' --body 'Update dependabot-updates branch via GitHub Actions' --label cicd_action,update_branch --assignee noaleclaire
